api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        json:
            mime_types: ['application/json']

        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']

        xml:
            mime_types: ['application/xml', 'text/xml']

        yaml:
            mime_types: ['application/x-yaml']

        csv:
            mime_types: ['text/csv']

    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

#        api_keys:
#            apiKey:
#                name: Authorization
#                type: header


